version: "3.9"
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: devpass
      POSTGRES_DB: appdb
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U dev -d appdb -h 127.0.0.1" ]
      interval: 5s
      timeout: 3s
      retries: 10
volumes:
  pg_data:
